name: Main

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Validate composer.json and composer.lock
        working-directory: ./app
        run: composer validate --strict

      - name: Install dependencies
        working-directory: ./app
        run: composer install --prefer-dist --no-progress

      - name: Run PSALM
        working-directory: ./app
        run: ./vendor/bin/phpstan

      - name: Run Tests
        working-directory: ./app
        run: ./vendor/bin/phpunit tests/
